### ISSUE TITLE
is there any example about setupclass and teardownclass? i'm totally confused.

### ISSUE THREAD

**Issue by wangrocky** [seleniumbase/SeleniumBase#317]
the original pytest setupclass and teardownclass is not working, pls provide some examples on how to make it work.
For example, I just wanna login once and execute testcases and do not want to login repeatly.

**Comment by mdmintz** [comment]
Hi @wangrocky , SeleniumBase overrides the setUp() and tearDown() methods, and uses those for spinning up and spinning down web browsers. You can have your own setUp() and tearDown() methods, but if you do, you'll need to call the ``super`` method for each one. See https://github.com/seleniumbase/SeleniumBase/blob/master/examples/boilerplates/base_test_case.py for the example.

**Comment by OthmanEmpire** [comment]
For future readers, here is an example of `setUpClass` and `tearDownClass` using SeleniumBase for a Django project.

```py
from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from seleniumbase import BaseCase

import fixtures                         # Just a file containing functions to generate data
import settings

class SeleniumTests(BaseCase, StaticLiveServerTestCase):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ADMIN = ("superuser01", "Passw0rd!")

    @classmethod
    def setUpClass(cls):
        super(SeleniumTests, cls).setUpClass()
        cls.superusers = fixtures.createSuperUsers()
        cls.users = fixtures.createUsers()

    @classmethod
    def tearDownClass(cls):
        super(SeleniumTests, cls).tearDownClass()

    def setUp(self):
        super(SeleniumTests, self).setUp()

    def tearDown(self):
        super(SeleniumTests, self).setUp()

    ### UTILITY

    def loginEndUserPage(self, username, password):
        self.open(f"{self.live_server_url}/")
        self.type("#username", username)
        self.type("#password", password)
        self.click("#login")

    ### TESTS: LOGIN PAGE

    def testLoginPage_adminCredentials_logsInSuccessfully(self):
        self.loginEndUserPage(*self.ADMIN)
        self.assert_element_not_present("#username")
        self.assert_element_not_present("#password")
```

**Comment by BarnabasSzabolcs** [comment]
This approach does not seem to work with Django 3.2.19, 
`object has no attribute 'settings_file'`
(and then once I add settings_file = None, it starts to ask for more and more variables that are not present)

**Comment by othmanalikhan** [comment]
Sounds like a bunch of things must have changed, sounds like the gist is no longer valid unfortunately. @BarnabasSzabolcs If you do end up finding the new way of doing things, if you could, it would be great to leave it in this issue for future readers.
